### ISSUE TITLE
Weather Simulation Suggestions

### ISSUE THREAD

**Issue by 38920** [niels747/2D-Weather-Sandbox#1]
-Hail
-Wind Shear or wind in general 
-flooding or water accumulation; some areas at lower places will be greener than others
-trees
-wind damage
- a rain gauge so you can see how much rain has fallen in an area
- a wind speed view

Thanks a bunch. I love this simulator.

**Comment by niels747** [comment]
Thank you for your suggestions. 

- Hail is already possible, It just needs some more tweaking. 
- Wind is also already there. It can develop naturally or you can use the slider in the fluid menu to force it.
- Flooding won't be implemented, this simulation focuses on the atmosphere.
- Trees might be added as a visual feature.
- Wind damage to what? Trees?

- Rain gauge is a good idea
- Wind speed view is already there. display mode 4: horizontal velocity

**Comment by Aerosoft8** [comment]
I think addition of a darker green brush that represent trees would be neat. That way radiation levels can be altered in different regions? Also i think a storm intensity display mode would be awesome. Anyways love your sandbox❤️

**Comment by Meso22** [comment]
Suggestions

- An option to change the height at which moisture doesn't dissipate.

-Blue and yellow flashes of light, (Lightning) in thunderstorms.

-Less swirly clouds?

Overall I am very glad to have found this simulator! It is very entertaining and fun to use👍

**Comment by 38920** [comment]
I think it is absoluteley neccesary to add pressure to this simulation, especially if you want to simulate hurricanes, tornadoes, and squall lines.
Another idea is to add a pressure view, and an anemometer.

**Comment by niels747** [comment]
Thanks for all of your input, I made list of things I will be implementing. https://github.com/niels747/Weather_Sim_4/blob/master/TODO.md

**Comment by KajlaKajla** [comment]
Hello Niels, my suggestion is to insert a wall as a brush tool so that it can simulate cities and increase evaporation from the  land

**Comment by oriolprogamer712** [comment]
Hello Niels, my suggestion is to insert houses,
towns,
and city
and the most important
people in the city in the houses and in the villages
and if it rains hard
let them go
people in the house

and if there are hurricanes
Y
tornadoes

that the people

run
a
their houses

towns

city

it is also necessary to add light inside the houses villas city

And another thing more

that if it rains that people carry umbrellas

me
sing for me

❤️

this simulation.

**Comment by niels747** [comment]
Sorry [oriolprogamer712](https://github.com/oriolprogamer712), But i'm not creating sim city...
I will however add more surface types, including cities.

**Comment by odvigajlo** [comment]
Niels, pleaaasee add hail

**Comment by JustLearninglol** [comment]
> 

LOL

**Comment by Meso22** [comment]
New Update!! Hell yes!!!

**Comment by JustLearninglol** [comment]
this is less than a suggestion but more of a question.. What is plane flying mode?

**Comment by niels747** [comment]
> this is less than a suggestion but more of a question.. What is plane flying mode?

You will be able to control a plane flying though the clouds, I think it could give an awesome perspective and sense of scale. Keep in mind that right now one cell is 40x40m so a a large plane would only be 2 cells wide. I will make it fly at scale speed and it will be affected by air currents.

**Comment by JustLearninglol** [comment]
OoO sounds cool! I just tested out the new version and it looks like when rain hits the ground the vegetation or greening doesnt grow, it just stays bone dry.

**Comment by niels747** [comment]
> OoO sounds cool! I just tested out the new version and it looks like when rain hits the ground the vegetation or greening doesnt grow, it just stays bone dry.

That's right, I made it like that on purpose. You can make your own vegitation where you want it.

**Comment by Aerosoft8** [comment]
@niels747 can you make the seafloor visual little deep. The current one is too shallow and I always had a hard time figuring land and sea when zoomed out

**Comment by Aerosoft8** [comment]
@niels747 Also, can you make the vegetation growth relative to the amount of rainfall received in the region. Like they grow on their own but at a slower rate than the previous version

**Comment by Aerosoft8** [comment]
@niels747 does rain affect fire

**Comment by niels747** [comment]
> @niels747 does rain affect fire

No, but I might add it in. Really intense rain should be able to put out fire, although I think this rarely happens in real life.

**Comment by Meso22** [comment]
Maybe make a barrier at the end of the map that deletes clouds so they don't fly through the map multiple times.

**Comment by niels747** [comment]
@Meso22 Do you mean that it also blocks airflow or just removes moisture? You can already do the first by just making a narrow but tall land wall. Removing moisture would be a bad idea because it would remove all the moisture in the map...

**Comment by Meso22** [comment]
@niels747 Ok thanks niel

**Comment by JustLearninglol** [comment]
Will you make lightning-sparked fires in intense lightning storms cuz looks like lightning is next on the list lol. Also a suggestion if this is a 100% visual effect then ignore this but if it isn't and there are charges then can you add a slide bar to control how many charges and how many lightning bolts/strikes lol.

**Comment by JustLearninglol** [comment]
![Screenshot 2022-07-04 10 46 41](https://user-images.githubusercontent.com/105594008/177200383-0cad9980-2f8b-496a-bbd7-137db5befff0.png)
So whenever I simulate hot desert climates which generally get above 100 degrees daily, this happens and I cannot see what comes after 100F such as for example its 105F but the green line goes too far and I cant see anything! please fix it!

**Comment by odvigajlo** [comment]
Suggestions:

Maybe upscale resolution option? it changes resolution of simulation but not changes size of simulation box, so simulation will be more realistic.

Possible fix for clouds be to smooth and not cumulus like:

IRL clouds move much slower than in sim, Now let's pretend (for example) that each vorticity vortex have speed of 100 mph in irl, and same speed in sim, that will cause behaviour as we see rn. Because irl clouds move slow while vortexes fast, which deforms them, but in sim clouds move fast but vortexes speed is same as irl, which makes clouds less deformed. Got point?
So fix is to make vorticity vortexes faster or make speed multiplier option (Sorry for bad English btw) I hope you understand this lol. Basically you should try speed up vorticty rotation speed

**Comment by odvigajlo** [comment]
> Thank you for your suggestions.
> 
> * Hail is already possible, It just needs some more tweaking.
> * Wind is also already there. It can develop naturally or you can use the slider in the fluid menu to force it.
> * Flooding won't be implemented, this simulation focuses on the atmosphere.
> * Trees might be added as a visual feature.
> * Wind damage to what? Trees?
> * Rain gauge is a good idea
> * Wind speed view is already there. display mode 4: horizontal velocity

if hail possible than why not to add it? or add into todo list?

**Comment by niels747** [comment]
@odvigajlo It's already in the sim! If you create a really heavy storm the ice particles will be lifted up heavily and grow so large they won't melt before they're at the surface, that's essentially what hail is.

**Comment by niels747** [comment]
From now on I would like you to ask your questions and share your ideas in the discussions tab.

**Comment by odvigajlo** [comment]
> @odvigajlo It's already in the sim! If you create a really heavy storm the ice particles will be lifted up heavily and grow so large they won't melt before they're at the surface, that's essentially what hail is.

oh i didn't noticed this lol, i remember how a lot of snow falled down from heavy storm while i played sim, i though that is bug lol
