### ISSUE TITLE
BUG with rainfall

### ISSUE THREAD

**Issue by KajlaKajla** [niels747/2D-Weather-Sandbox#10]
After I start the simulation a couple of times and save the simulation, I start it again and the precipitation weakens so much that there is hardly any, and when I go from left to right, regardless of whether the droplet is on, the precipitation disappears, they only have virga.
![unexpected virga](https://user-images.githubusercontent.com/105985357/178008143-fef3d013-34e3-4986-b407-0d0aa147df56.png)
![preuzmi (4)](https://user-images.githubusercontent.com/105985357/178008156-b25d4d31-9f62-49a5-92df-c655401f47e8.png)

**Comment by JustLearninglol** [comment]
I get that glitch too. It will probably be weeks until its fixed or until theres another update

**Comment by wilburcoding** [comment]
@niels747 is this fixed yet

**Comment by niels747** [comment]
I'm not sure, but i'm planning to rework the whole precipitation system soon anyway
