### ISSUE TITLE
Terrain Generates 

### ISSUE THREAD

**Issue by Weathermandavid** [niels747/2D-Weather-Sandbox#104]
I noticed that land and seas, this includes mountains and hills that generate every time i pull down the settings menu on the right-side of the simulator. This is quite annoying and should we fixed ASAP. Thanks.

**Comment by niels747** [comment]
This was fixed in commit: https://github.com/niels747/2D-Weather-Sandbox/commit/08ff7576c48baadcdc97aae38bb07c572ef83999
