### ISSUE TITLE
Stuck on "setting up textures" 

### ISSUE THREAD

**Issue by selenium2106** [niels747/2D-Weather-Sandbox#124]
I have a new problem, it happened to me a while ago and I have not been able to find a solution, it loads normally up to 80%, there it gets stuck, it should be noted that the web version loads normally, But the local version does not work. PS: I'm on Linux and using Xampp as a localhost server.

**Comment by niels747** [comment]
Read the instructions how to run locally, you need to use a local server, don't just open the index.html!
