### ISSUE TITLE
trying to run simulator from github source code

### ISSUE THREAD

**Issue by Westerstaad** [niels747/2D-Weather-Sandbox#19]
Whenever I run the index.html with my browser, I try to start a simulation and it get stuck on "Setting up WebGL" Do you know why it does this?
![image](https://user-images.githubusercontent.com/113951205/191138807-b40571ea-075a-4a13-b14a-0557d1deef5e.png)

**Comment by niels747** [comment]
Open the console (F12) and show me the error you're getting. 
Also tell me your system specs and browser.

**Comment by Westerstaad** [comment]
Windows 10 Pro
NVIDIA Quadro K4200
I5-7500K
8 gigs of ram
Opera
![image](https://user-images.githubusercontent.com/113951205/191340382-b8adebe8-f395-4519-938b-140e6b143421.png)

**Comment by niels747** [comment]
Now I get what you are trying to do. JavaScript can't query for local files. This would be a serious breach of security. Thats why you can't just run it from index.html. You have to host it locally using a server. The easiest way (I use this) is to use VS code with the live server extension. It's really easy to install.

**Comment by Westerstaad** [comment]
Thanks, it works now.
