### ISSUE TITLE
Snow not showing on ground

### ISSUE THREAD

**Issue by panagiotisLadis** [niels747/2D-Weather-Sandbox#51]
When it snows there is no snow on the ground :(

My pc specs:

i5 12450H
RTX 3050 4GB
16GB RAM

**Comment by wilburcoding** [comment]
It takes a while to accumulate

**Comment by niels747** [comment]
> 

What browser and OS?

**Comment by panagiotisLadis** [comment]
My Browser is Chrome 
Windows 11

**Comment by niels747** [comment]
hardware specs and OS?

**Comment by panagiotisLadis** [comment]
![bug_snow_ground](https://user-images.githubusercontent.com/60401937/211061269-93dd0b60-6356-4d65-a466-426ed55dda17.png)

My pc specs:

i5 12450H
RTX 3050 4GB
16GB RAM

OS: Windows 11
Browser: Chrome

**Comment by niels747** [comment]
But it is showing, if you mean the spottyness, that's normal. It takes some time to cover everything, (just like minecraft)

**Comment by panagiotisLadis** [comment]
it doesn't change at all, it stays like this forever without being covered with snow

**Comment by niels747** [comment]
Ow that is a bug. Where did the initial snow come from then?

**Comment by panagiotisLadis** [comment]
when it snows, it will start to snow only in those places you saw. This always happened to me and I have changed 2 computers, I thought that this error only happened on my old computer, that's why I didn't report anything.

**Comment by niels747** [comment]
Okay, very wierd... I ran it on an RTX 3070 in windows 10 Chrome and there where no problems! maybe caused by windows 11... IDK?

**Comment by panagiotisLadis** [comment]
It also happened on windows 10...

**Comment by panagiotisLadis** [comment]
i dont know IDK :(

**Comment by niels747** [comment]
IDK either, sorry. I can only fix problems I can reproduce.

**Comment by niels747** [comment]
Actually the only thing I can imagine is that your browser is not actually using the RTX 3050...
On laptops with both integraded and dedicated graphics the browser is usually using the integrated graphics by default.
(Integrated graphics have caused some wierd issues for me)
Please check in task manager that the RTX3050 has high gpu usage when running the sim

**Comment by panagiotisLadis** [comment]
okkk

**Comment by panagiotisLadis** [comment]
I fixed it, thank you very much, I didn't realize that it was running with the processor card, now it runs much faster

**Comment by niels747** [comment]
Awesome, i'm so glad I could help you with that! Have fun!
