### ISSUE TITLE
Land creation bug

### ISSUE THREAD

**Issue by wilburcoding** [niels747/2D-Weather-Sandbox#52]
I was creating some land but after I stopped holding down my mouse, the land continued to move and expand the direction I was making land.
This is on Chrome on a Dell Computer

**Comment by wilburcoding** [comment]
I will try to get a image

**Comment by niels747** [comment]
Did this happen just once? Maybe you could show a picture / video?

**Comment by niels747** [comment]
Interesting, but imposible for me to solve if I can't reproduce it.
