### ISSUE TITLE
Precipitation not spawning properly

### ISSUE THREAD

**Issue by 38920** [niels747/2D-Weather-Sandbox#53]
For me, the only rainfall is in some clouds as a tiny square. Here is a picture:

![Screenshot 2023-01-03 3 35 37 PM](https://user-images.githubusercontent.com/105367931/210437224-3f1a68a6-9efb-4e08-bdab-5661f998c596.png)

**Comment by 38920** [comment]
Also during the day, everything looks really dark. I've turned the exposure up with no change.

**Comment by niels747** [comment]
Please tell me all your system specs and browser!

**Comment by 38920** [comment]
Browser: Google Chrome 
CPU Processor: MediaTek MT8183 (2.0 GHz base frequency, 1 MB cache, 8 cores)1,2

**Comment by 38920** [comment]
It can [simulate] wave clouds, which is very impressive. 
![Screenshot 2023-01-09 10 48 30 AM](https://user-images.githubusercontent.com/105367931/211365042-18900018-4893-492c-92f7-c8f28b446baa.png)

**Comment by 38920** [comment]
Here is more hardware specs; I believe I gave the wrong ones.
8GB RAM
OS: Chrome-OS
Mali G72 
My chromebook is also up to date. 
Weather_Sim_4 worked well, and I can run 6000*300  resolution in real time without a problem.

**Comment by niels747** [comment]
Interesting that chromebook causes this problem... I can't fix what I can't reproduce, so I would have to go into an electronics store and try it on their display model chromebooks...
can you open the console in chrome and see if there are any error messages?

**Comment by 38920** [comment]
I am unable to open the console, as I am on a managed Chromebook. 

I don't think its a bug with the code, rather some of it isn't supported by the current update my chromebook has.

I have also checked, and It says that ChromeOS is in 108.0.5359.172, but my chromebook is in 108.0.5359.111. 

I will try to clear my cache to get room for the new update.

**Comment by niels747** [comment]
Okay, noting I can do for you right now...
