### ISSUE TITLE
Weird Land bug on creation of new sim

### ISSUE THREAD

**Issue by wilburcoding** [niels747/2D-Weather-Sandbox#57]
![image](https://user-images.githubusercontent.com/66228004/211338886-4ee5a2b6-8228-4040-befc-22d9f69b8871.png)
This happens when i create a new sin on the school computer.
idk what the black thing is bug it keeps moving left and covers up all the land
![image](https://user-images.githubusercontent.com/66228004/211339126-71be3085-c199-4822-b52a-df98ece805fb.png)
I believe this is a separate bug from the other issue i created a while ago.
This is on Chrome on Windows 10 Education on a Dell Computer

**Comment by niels747** [comment]
If you can't give any more information on the system I can't help you with this.
