### ISSUE TITLE
Snow is Yellow 

### ISSUE THREAD

**Issue by MET905** [niels747/2D-Weather-Sandbox#65]
![bug](https://user-images.githubusercontent.com/113155608/215643622-2f2a06f8-6d17-455b-a4c1-d59a53a2bca4.png)

**Comment by MET905** [comment]
This bug made me laugh, all I could think of was pee in the snow lol!

**Comment by niels747** [comment]
Ow, that's not right indeed. Please tell me your system and browser specs.

**Comment by MET905** [comment]
Sorry for the late response man, I'm using Firefox and I have a gaming PC, I can't remember the specs as I'm not at my Computer right now.

**Comment by JustLearninglol** [comment]
I think it’s god’s pee

**Comment by niels747** [comment]
Since I am the "god" I can confirm it's not.
In all seriousness I think this issue might only happen on AMD radeon gpu's...

**Comment by MET905** [comment]
Weird, this bug started right after your last update. My PC has a NVIDA GeoForce GTX 1070

**Comment by mesochaser2425** [comment]
i too have the same problem

**Comment by MET905** [comment]
Im glad im not the only one.

**Comment by niels747** [comment]
> Weird, this bug started right after your last update. My PC has a NVIDA GeoForce GTX 1070

That's really wierd since I also have a GTX 1070 and I obviously don't have that problem. Are you sure your browser isn't using integrated graphics you might also have?

**Comment by mesochaser2425** [comment]
i have radeon 490 xfx 
\

**Comment by MET905** [comment]
I tried that Still no change. My browser is using the highest performance.

**Comment by Aerosoft8** [comment]
I see this yellow color when snow shifts to rain. Most likely a bug in the code?

**Comment by MET905** [comment]
100% code related

**Comment by niels747** [comment]
I found the issue, it only happened if you changed the stock snow density to more than 0.5!

It is displayed yellow when the density is > 0.5 and it's pure ice:
https://github.com/niels747/2D-Weather-Sandbox/blob/dd74c76ff33689c13d7ee1b5a8a599d50ee20fae/shaders/fragment/precipDisplayShader.frag#L35
Will commit fix now

**Comment by MET905** [comment]
Thank you Niels
