### ISSUE TITLE
Simulation screen blackout

### ISSUE THREAD

**Issue by Aerosoft8** [niels747/2D-Weather-Sandbox#66]
Hi,

I faced this simulation blackout issue recently and it happens after several minutes of playing. It started happening after a previous update and I'm not sure exactly when it started happening.

![weathersi](https://user-images.githubusercontent.com/105531208/216838208-1e694bb8-222a-4608-bb88-a4871ca13b0d.JPG)

**Comment by niels747** [comment]
System Specs?
Hardware, OS, browser, etc.

**Comment by niels747** [comment]
Can't reproduce
