### ISSUE TITLE
Weather station data issue

### ISSUE THREAD

**Issue by wilburcoding** [niels747/2D-Weather-Sandbox#70]
Weather station temperature data only shows when I switch to temperature field after creation

**Comment by wilburcoding** [comment]
Could be because weather station update every once in a while?

**Comment by niels747** [comment]
They update every 600 iterations, no matter what view mode you are in. I did this because reading from the texture is a big performance hit.
https://github.com/niels747/2D-Weather-Sandbox/blob/c30527a96bf965f23a9753aa04f93defa29db0a9/app.js#L2768
