### ISSUE TITLE
Maybe a bug I am not sure?

### ISSUE THREAD

**Issue by Meso22** [niels747/2D-Weather-Sandbox#8]
This strange cloud formation occurs when I set the global heating  to 0.0001 or over it eventually gets so big it covers the entire area.
![234](https://user-images.githubusercontent.com/105577122/177460442-cd109ebb-991e-409e-876d-343b72b2dd6e.png)
![235](https://user-images.githubusercontent.com/105577122/177460691-0e8ffe4a-5ce0-4e1c-99e9-fe5680380c9e.png)
![236](https://user-images.githubusercontent.com/105577122/177460707-4ca73cfb-7f1c-445a-926e-6d2ade1c94b4.png)

**Comment by odvigajlo** [comment]
I think strange cloud formations not a bug, just how heat affects clouds. But as far as i know if clouds cover entire area this is bug, that happens when there is "overheat", Niels aware from.

**Comment by niels747** [comment]
The temperature at the top ( 12000m ) is locked to -60C , So if you heat the atmosphere below it will convect and carry moisure up there and create clouds. This is not a bug, it's just unrealistic conditions that you created.

**Comment by Meso22** [comment]
@niels747  Thanks niels I was just trying to make the surface level temperature hotter by using the global heating because I couldn't find another way to do it, if there is another way please let me know.

**Comment by niels747** [comment]
You can use the temperature tool and turn on Whole Width Brush to heat up any layer you want

**Comment by Meso22** [comment]
Awesome that seemed to work very well!

**Comment by Meso22** [comment]
I will close this down now if that's ok
