### ISSUE TITLE
error con WebGL

### ISSUE THREAD

**Issue by selenium2106** [niels747/2D-Weather-Sandbox#83]
It doesn't work because my browser says it doesn't support webgl 2.0, even though I have an rtx1050 with its updated drivers

**Comment by niels747** [comment]
Please speak english here.
What browser are you using?

**Comment by selenium2106** [comment]
It does not work because my browser says that it does not support webgl 2.0, even though I have an rtx1050 with its updated drivers updated drivers, I used Chrome and Edge, but none of it works

**Comment by Aerosoft8** [comment]
I think maybe webgl is not enabled in browser? I think they have the toggle to use hardware acceleration
