### ISSUE TITLE
Crash simulation

### ISSUE THREAD

**Issue by GRolLevente** [niels747/2D-Weather-Sandbox#91]
After starting the simulation, within a given time, starting from a point, the simulation crashes. I experience this with saved and loaded files. This does not happen with a newly started simulation. I'm running the latest Google Chrome. Haven't had this problem for a few weeks. 
Video card: AMD Radeon RX 6700 XT.

Presentation of the error: https://drive.google.com/drive/folders/1ew0geS_rGDdM1-fkpgN237SZmgNsQMIs?usp=sharing

![WSbug](https://github.com/niels747/2D-Weather-Sandbox/assets/118711061/0fbc2530-f287-419e-8e15-3d9373466879)

**Comment by niels747** [comment]
Hi, thanks for posting the issue and sorry for my late response.
I loaded your savefile and it works perfectly fine on my system. I have seen this kind of bug before on intel and amd gpu's, but never on Nvidea. I don't know what causes it, it seems like the gpu makes random mistakes sometimes, resulting in NaN values spreading all over the map.

**Comment by GRolLevente** [comment]
Thank you very much for your reply.  I wanted to write that the problem no longer occurs with the new update.  Anyway, the special update with 500 subscribers was really cool.  Thanks for everything!  :)
