### ISSUE TITLE
Selection menus cannot be opened

### ISSUE THREAD

**Issue by GRolLevente** [niels747/2D-Weather-Sandbox#98]
The error has been present for maybe a day or two. The menus do not open by clicking the mouse. This is also demonstrated in the attached video.

https://github.com/niels747/2D-Weather-Sandbox/assets/118711061/2e4076e4-aaf8-4e2e-934a-445619a00705

**Comment by niels747** [comment]
Fixed by reming the ".preventDefault();" on the mousedown event

**Comment by GRolLevente** [comment]
Thank you very much for correcting the error. Menus now work.
